# Generated by Django 3.1.3 on 2020-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='restaurent_name',
            new_name='restaurent_id',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
