# Generated by Django 3.1.3 on 2020-11-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productsapp', '0003_auto_20201129_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='is_present',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
