# Generated by Django 3.1.3 on 2020-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productsapp', '0004_restaurent_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='location',
            field=models.TextField(default='', max_length=40),
        ),
    ]
