# Generated by Django 3.1.3 on 2020-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productsapp', '0007_auto_20201202_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_products',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
