# Generated by Django 3.1.3 on 2021-01-01 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Productsapp', '0008_auto_20201202_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRecommendations',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
