# Generated by Django 3.1.3 on 2021-01-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterUserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_customer',
        ),
    ]
